"""add trip_options and rename notes to user_preferences

Revision ID: 09875546bab0
Revises: beaa58a4a09f
Create Date: 2026-06-29 13:41:02.026352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09875546bab0'
down_revision: Union[str, Sequence[str], None] = 'beaa58a4a09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_request_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=False),
    sa.Column('estimated_budget', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trip_requests', sa.Column('user_preferences', sa.String(), nullable=True))
    op.drop_column('trip_requests', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_requests', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trip_requests', 'user_preferences')
    op.drop_table('trip_options')
    # ### end Alembic commands ###
